
version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: r6guides-mysql
    environment:
      MYSQL_DATABASE: r6guides
      MYSQL_USER: r6user
      MYSQL_PASSWORD: maxwell
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
