version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: r6guides-postgres
    environment:
      POSTGRES_DB: r6guides
      POSTGRES_USER: r6user
      POSTGRES_PASSWORD: r6password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

